apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app
spec:
  endpoints:
    - port: http
      interval: 5s
#  namespaceSelector:
#    matchNames:
#      - crane-system
  selector:
    matchLabels:
      app: sample-app