apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.36.1
  name: prometheus-k8s
rules:
  - verbs:
      - get
      - list
      # ts=2022-08-25T12:59:17.528Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167: Failed to watch *v1.Pod: unknown (get pods)"
      - watch
    apiGroups:
      - ''
    resources:
      - nodes/metrics
      - pods
      - services
      - endpoints
  - verbs:
      - get
    nonResourceURLs:
      - /metrics
